# Generated by Django 5.2.7 on 2025-11-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_grader', '0002_question_paper_grade_confere_59220a_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
